//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.quantityInStock = new HashSet<quantityInStock>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int QuantityInTotal { get; set; }
        public string Article { get; set; }
        public byte[] Image { get; set; }
        public int ManufacturerId { get; set; }
        public int СountryId { get; set; }
        public int TypeId { get; set; }
        public decimal Price { get; set; }
        public string code { get; set; }
        public string section { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
        public virtual ICollection<quantityInStock> quantityInStock { get; set; }
    }
}
