//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quantityInStock
    {
        public int idProduct { get; set; }
        public int idStorage { get; set; }
        public int quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
