//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public Storage()
        {
            this.quantityInStock = new HashSet<quantityInStock>();
        }
    
        public int idNumber { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<quantityInStock> quantityInStock { get; set; }
    }
}
